<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_tools"
 *
 * Auto generated by Extension Builder 2017-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Tools',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Maximilian Fäßler',
	'author_email' => 'maximilian@faesslerweb.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '8.7.13',
	'constraints' => [
		'depends' => [
            'typo3' => '7.6.0-7.6.99',
			'rkw_basics' => '8.7.0-8.7.99',
			'rkw_projects' => '8.7.0-8.7.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
